name: Go

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    
    - name: Install libasound2
      run: sudo apt install libasound2-dev

    - name: Generate build files
      uses: thatisuday/go-build-action@v1
      with:
        platforms: "linux/amd64, linux/arm, linux/arm64, darwin/amd64, darwin/arm64, windows/amd64, windows/arm64"
        name: "radio"
        compress: "true"
        dest: "dist"
      
    - name: Upload a Build Artifact
      uses: actions/upload-artifact@v2.3.1
      with:
        # Artifact name
        # name:
        # optional, default is artifact
        # A file, directory or wildcard pattern that describes what to upload
        path: dest/*.tar.gz
