name: Go

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    
    - name: Install libasound2
      run: sudo apt install libasound2-dev
      
    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.17
        
    - name: Build linux amd64
      run: env GOOS=linux GOARCH=amd64 CGO_ENABLED=1 go build -v -buildmode exe -o dest/radio-linux-amd64 .
      
    - name: Build linux 386
      run: env GOOS=linux GOARCH=386 CGO_ENABLED=1 go build -v -buildmode exe -o dest/radio-linux-386 .
      
    - name: Build windows amd64
      run: env GOOS=windows GOARCH=amd64 CGO_ENABLED=1 go build -v -buildmode exe -o dest/radio-windows-amd64 .
      
    - name: Upload linux amd64 artifact
      uses: actions/upload-artifact@v2.3.1
      with:
        name: linux-amd64
        path: dest/radio-linux-amd64
        
    - name: Upload linux 386 artifact
      uses: actions/upload-artifact@v2.3.1
      with:
        name: linux-386
        path: dest/radio-linux-386
        
    - name: Upload windows amd64 artifact
      uses: actions/upload-artifact@v2.3.1
      with:
        name: windows-amd64
        path: dest/radio-windows-amd64
