name: Go

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    
    - name: Install libasound2
      run: sudo apt install libasound2-dev
      
    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.17
        
    - name: Build linux amd64
      run: env GOOS=linux GOARCH=amd64 CGO_ENABLED=1 go build -v -buildmode exe -o dest/radio-linux-amd64 .
      
    - name: Upload a Build Artifact
      uses: actions/upload-artifact@v2.3.1
      with:
        # Artifact name
        # name:
        # optional, default is artifact
        # A file, directory or wildcard pattern that describes what to upload
        path: dest/*
